In [11]:
import numpy as np

X = np.array([[12,7,3],[4 ,5,6],[7 ,8,9]])

Y = np.array([[5,8,1,2],[6,7,3,0],[4,5,9,1]])


result = np.zeros((np.shape(X)[0], np.shape(Y)[1]))

for i in range(np.shape(X)[0]):
   # iterate through columns of Y
    for j in range(np.shape(Y)[1]):
       # iterate through rows of Y
        for k in range(len(Y)):
           result[i][j] += X[i][k] * Y[k][j]





kontrol = np.matmul(X,Y)


print(result, kontrol, sep = ', ')



[[114. 160.  60.  27.]
 [ 74.  97.  73.  14.]
 [119. 157. 112.  23.]], [[114 160  60  27]
 [ 74  97  73  14]
 [119 157 112  23]]
