In [2]:
import numpy as np
from copy import deepcopy

In [3]:
# Create Matrix
def func1(Row,Column): # Function starts
    # Check if the input is a positive integer
    if Row < 1 or Column < 1 or type(Row) != int or type(Column) != int:
        print("Please enter a positive integer")
        return
    # Create a matrix with the given size
    if Row == Column: # If Row = Column
        # Create a zero square matrix
        mat1= np.zeros((Row,Column))
        print('Enter the elements of matrix.\n')
        for it1 in range(Row):
            for it2 in range(Column):
                str1='Enter element [%d][%d]: ' %(it1+1,it2+1)
                mat1[it1,it2] = float(input(str1))
                  
        return mat1

    else:
        print('Matrix is not square!')
        return

In [4]:
def func2(mat):
    if mat.shape[0] < 1:
        print("Please enter a positive integer")
        return
    if (mat == np.eye((mat.shape[0]))).all():
        print('Unit matrix \n')
    else:
        print('Not unit matrix \n')
        

In [5]:
def func3(mat1, mat2):
    if (mat2 == np.eye(mat1.shape[0])).all() or (mat1 == np.eye(mat2.shape[0])).all():
        quit
    
    elif mat1.shape[1] == mat2.shape[0]:
        print(mat1@mat2)

    return


In [ ]:
def minor(mat, i, j):
    mat = arr[:]
    mat_r = np.delete(mat, (i), 0)
    mat_c = np.delete(mat_r, (j), 1)
    return mat_c

In [155]:
def det(mat):
    
    if len(mat) == 1:
        return mat[0][0]
    if len(mat) == 2:
        return mat[0][0]*mat[1][1] - mat[0][1]*mat[1][0]
    sonuc = 0
    for i in range(0,len(mat)):
        m = minor(mat,0,i)
        sonuc =sonuc + ((-1)**i)*mat[0][i] * det(m)
    return sonuc

   
                
      
        

In [156]:
det(mat1)

-1.0

In [111]:
def minor(arr,i,j):
    c = arr[:]
    c = np.delete(c, (i),axis=0)
    return [np.delete(row, (j),axis=0) for row in (c)]

In [154]:
mat1

array([[2., 3., 4.],
       [2., 2., 1.],
       [1., 1., 1.]])

In [116]:
minor(mat1,0,2)

[array([2., 2.]), array([1., 1.])]

In [61]:
np.delete(mat1,0,0)

array([[2., 2., 1.],
       [1., 1., 1.]])

In [81]:
np.delete(np.delete(mat1,0,0),2,1)

array([[2., 2.],
       [1., 1.]])

In [100]:
mat1

array([[2., 3., 4.],
       [2., 2., 1.],
       [1., 1., 1.]])

In [60]:
np.delete(np.delete(mat1,0,0),-0,1)

array([[2., 1.],
       [1., 1.]])

In [110]:
mat1[:]

array([[2., 3., 4.],
       [2., 2., 1.],
       [1., 1., 1.]])

In [101]:
for it1 in range(3):
        isaret = (-1) ** (it1 % 2)
        for it1 in range(len(mat1)):

                isaret = (-1) ** (it1 % 2)

                q =np.array([])

                cizgi = mat1[:1]

                q += np.delete(np.delete(mat1,0,0),it1,1)*isaret*cizgi[0,it1]

ValueError: operands could not be broadcast together with shapes (0,) (2,2) (0,) 

In [104]:
q = np.delete(np.delete(mat1,0,0),0,1)*1*cizgi[0,0] + np.delete(np.delete(mat1,0,0),1,1)*-1*cizgi[0,1] + np.delete(np.delete(mat1,0,0),2,1)*1*cizgi[0,2]

print(q)

[[6. 7.]
 [3. 3.]]


In [109]:
np.delete(np.delete(mat1,0,0),2,1)

array([[2., 2.],
       [1., 1.]])

In [107]:
cizgi[0,2]

4.0

In [97]:
func4(mat1)

ValueError: operands could not be broadcast together with shapes (0,) (2,2) (0,) 

In [9]:
mat1 = func1(3,3)

Enter the elements of matrix.



In [20]:
mat1[:1]

array([[2., 3., 4.]])

In [21]:
mat1

array([[2., 3., 4.],
       [2., 2., 1.],
       [1., 1., 1.]])

In [23]:
r = np.array([1,2,3])

1