In [165]:
import numpy as np
from copy import deepcopy

In [5]:
# Create Matrix
def func1(Row,Column): # Function starts
    # Check if the input is a positive integer
    if Row < 1 or Column < 1 or type(Row) != int or type(Column) != int:
        print("Please enter a positive integer")
        return
    # Create a matrix with the given size
    if Row == Column: # If Row = Column
        # Create a zero square matrix
        mat1= np.zeros((Row,Column))
        print('Enter the elements of matrix.\n')
        for it1 in range(Row):
            for it2 in range(Column):
                str1='Enter element [%d][%d]: ' %(it1+1,it2+1)
                mat1[it1,it2] = float(input(str1))
                  
        return mat1

    else:
        print('Matrix is not square!')
        return

In [2]:
def func2(mat):
    if mat.shape[0] < 1:
        print("Please enter a positive integer")
        return
    if (mat == np.eye((mat.shape[0]))).all():
        print('Unit matrix \n')
    else:
        print('Not unit matrix \n')
        

In [32]:
def func3(mat1, mat2):
    if (mat2 == np.eye(mat1.shape[0])).all() or (mat1 == np.eye(mat2.shape[0])).all():
        quit
    
    elif mat1.shape[1] == mat2.shape[0]:
        print(mat1@mat2)

    return


In [211]:
def func4(mat):
    a = list(range(len(mat)))

    if mat.shape[0] != mat.shape[1] or (mat == np.eye(mat.shape[0])).all():
        print('This matrix is either a non square or an identity matrix')
        quit

    elif len(mat) == 2:
        det = mat[0][0] * mat[1][1] - mat[1][0] * mat[0][1]
        return det
        quit

    for i in a:
        isaret = (-1) ** (i % 2)

    

    else:
        for it1 in (a):

            new = np.zeros((len(mat)-1,len(mat)-1))


            np.delete(np.delete(mat2,0,0),it1,1)

            det1 = 0

            det1 += isaret*np.delete(np.delete(mat2,0,0),it1,1)

        return det1
                
      
        

In [197]:
v = np.array([[2,3],[5,7]])

In [213]:
func4(mat2)

array([[ 0., -3.],
       [ 0.,  0.]])

In [215]:
mat2

array([[ 1.,  2.,  3.],
       [ 0., -3., -6.],
       [ 0.,  0.,  0.]])

In [52]:
a = mat2[:1]

In [55]:
a

array([[1., 2., 3.]])

In [58]:
a[0,2]

3.0

In [89]:
mat2[-2:,:-1]

array([[4., 5.],
       [7., 8.]])

In [130]:
mat2

array([[ 1.,  2.,  3.],
       [ 0., -3., -6.],
       [ 0.,  0.,  0.]])

In [155]:
b = np.delete(mat2,0,1)

In [146]:
b

array([[ 0., -3., -6.],
       [ 0.,  0.,  0.]])

In [151]:
c = np.delete(b,0,1)

In [152]:
c

array([[-3., -6.],
       [ 0.,  0.]])

In [159]:
np.delete(np.delete(mat2,0,0),2,1)

array([[ 0., -3.],
       [ 0.,  0.]])

In [119]:
mat2[1][1]

5.0

In [175]:
def func44(mat):
    new = deepcopy(mat)
    for it1 in range(len(mat)):
        new += (np.delete(np.delete(mat,0,0),it1,1))
    return new

In [176]:
func44(mat2)

ValueError: operands could not be broadcast together with shapes (3,3) (2,2) (3,3) 

In [188]:
for it1 in (1,2,3):

            new = np.zeros((len(mat)-1,len(mat)-1))


            new[it1] = np.delete(np.delete(mat2,0,0),it1,1)

            cofactor[it1] = -1**(it1)

            det += cofactor[it1]*new[it1]

IndexError: index 1 is out of bounds for axis 0 with size 1