## First Question

In [1]:
import numpy as np

#create your first matrix

lst= [ ] 
n = int(input("Enter number of elements : ")) 
  
for i in range(0,n):
    g = [float(input()), float(input())]
    lst.append(g)
      
print(lst)

a = np.array(lst)

Enter number of elements : 2
2
2
2
2
[[2.0, 2.0], [2.0, 2.0]]


In [2]:
a


array([[2., 2.],
       [2., 2.]])

In [3]:
#create your second matrix

lst2= [ ] 
n = int(input("Enter number of elements : ")) 
  
for i in range(0,n):
    g = [float(input()), float(input())]
    lst2.append(g)
    
print(lst2)

b = np.array(lst2)

Enter number of elements : 2
2
2
3
4
[[2.0, 2.0], [3.0, 4.0]]


In [4]:
b

array([[2., 2.],
       [3., 4.]])

In [5]:
print(np.dot(a, b))

[[10. 12.]
 [10. 12.]]


## Second Question

Inner matrix is what we know as dot product but what exactly is the outer product?

suppose you have u =<u1, u2, u3>, v =<v1, v2, v3> dot product of these two would be $  u^T   v$

but you might not know is outer product of these two would be $ u    v^T = <[u1*v1,u1*v2,u1*v3];[u2*v1,u2*v2,u2*v3];[u3*v1,u3*v2,u3*v3]> $

In [18]:
import numpy as np
  
R = float(input("Enter the number of rows:"))
C = float(input("Enter the number of columns:"))
  
  
print("Enter the entries in a single line (separated by space): ")
  
# User input of entries in a 
# single line separated by space
entries = [float(input()), float(input())]
  
# For printing the matrix
b = np.array(entries).reshape(R, C)
print(b)

b = np.array(b)

Enter the number of rows:2
Enter the number of columns:2
Enter the entries in a single line (separated by space): 
2.0 2.0 2.0 2.0


ValueError: could not convert string to float: '2.0 2.0 2.0 2.0'

In [21]:
import numpy as np
  
R = int(input("Enter the number of rows:"))
C = int(input("Enter the number of columns:"))
  
  
print("Enter the entries in a single line (separated by space): ")
  
# User input of entries in a 
# single line separated by space
entries = list(map(int, input().split()))
  
# For printing the matrix
matrix = np.array(entries).reshape(R, C)
print(matrix)

Enter the number of rows:2 
Enter the number of columns:2
Enter the entries in a single line (separated by space): 
2 2 2 2
[[2 2]
 [2 2]]


In [22]:
#çalınan kodların kaynağı:

#https://www.quora.com/What-does-the-following-line-mean-in-Python-list-map-int-input-strip-split-I
#https://www.geeksforgeeks.org/take-matrix-input-from-user-in-python/

import numpy as np
  
R = int(input("Enter the number of rows:"))
C = int(input("Enter the number of columns:"))
  
  
print("Enter the entries in a single line (separated by space): ")
  
# User input of entries in a 
# single line separated by space
entries = list(map(int, input().split()))
  
# For printing the matrix
matrix2 = np.array(entries).reshape(R, C)
print(matrix2)

Enter the number of rows:2
Enter the number of columns:2
Enter the entries in a single line (separated by space): 
2 6 5 7
[[2 6]
 [5 7]]


In [23]:
print(np.outer(matrix, matrix2))

[[ 4 12 10 14]
 [ 4 12 10 14]
 [ 4 12 10 14]
 [ 4 12 10 14]]


## Third Question

In [28]:
R = int(input("Enter the number of rows:"))
C = int(input("Enter the number of columns:"))
  
  
print("Enter the entries in a single line (separated by space): ")
  
# User input of entries in a 
# single line separated by space
entries = list(map(int, input().split()))
  
# For printing the matrix
matrix3 = np.array(entries).reshape(R, C)
print(matrix3)


R = int(input("Enter the number of rows:"))
C = int(input("Enter the number of columns:"))
  
  
print("Enter the entries in a single line (separated by space): ")
  
# User input of entries in a 
# single line separated by space
entries = list(map(int, input().split()))
  
# For printing the matrix
matrix4 = np.array(entries).reshape(R, C)
print(matrix4)


print(np.cross(matrix3, matrix4))

Enter the number of rows:1
Enter the number of columns:3
Enter the entries in a single line (separated by space): 
1 2 3
[[1 2 3]]
Enter the number of rows:1
Enter the number of columns:3
Enter the entries in a single line (separated by space): 
2 3 5
[[2 3 5]]
[[ 1  1 -1]]


## Fourth Question


In [29]:
R = int(input("Enter the number of rows:"))
C = int(input("Enter the number of columns:"))
  
  
print("Enter the entries in a single line (separated by space): ")
  
# User input of entries in a 
# single line separated by space
entries = list(map(int, input().split()))
  
# For printing the matrix
hü = np.array(entries).reshape(R, C)

hüü = np.linalg.det(hü)

print(hü,hüü, sep = '--')

Enter the number of rows:2
Enter the number of columns:2
Enter the entries in a single line (separated by space): 
2 3 7 1
[[2 3]
 [7 1]]---18.999999999999996


## Fifth Question


In [30]:
#Einstein's summation convention'ın ne olduğunu anlayamadım

## Sixth Question

In [31]:
R = int(input("Enter the number of rows:"))
C = int(input("Enter the number of columns:"))
  
  
print("Enter the entries in a single line (separated by space): ")
  
# User input of entries in a 
# single line separated by space
entries = list(map(int, input().split()))
  
# For printing the matrix
matrix5 = np.array(entries).reshape(R, C)


R = int(input("Enter the number of rows:"))
C = int(input("Enter the number of columns:"))
  
  
print("Enter the entries in a single line (separated by space): ")
  
# User input of entries in a 
# single line separated by space
entries = list(map(int, input().split()))
  
# For printing the matrix
matrix6 = np.array(entries).reshape(R, C)


print(matrix5, matrix6, np.inner(matrix5, matrix6), sep = 'oooooooooo')





Enter the number of rows:2
Enter the number of columns:3
Enter the entries in a single line (separated by space): 
1 2 3 4 5 6
Enter the number of rows:2
Enter the number of columns:3
Enter the entries in a single line (separated by space): 
7 8 9 10 11 12
[[1 2 3]
 [4 5 6]]oooooooooo[[ 7  8  9]
 [10 11 12]]oooooooooo[[ 50  68]
 [122 167]]


## Seventh Question


In [33]:
D = np.array([[4, 2, 2],[2, 4, 2],[2, 2, 4]])

w, v =np.linalg.eig(D)

In [34]:
w #eigenvalues


array([2., 8., 2.])

In [35]:
v #eigenvectors full list

array([[-0.81649658,  0.57735027, -0.32444284],
       [ 0.40824829,  0.57735027, -0.48666426],
       [ 0.40824829,  0.57735027,  0.81110711]])

In [38]:
v[:, 0] #first eigen vector

array([-0.81649658,  0.40824829,  0.40824829])

In [40]:
v[:, 2] #last eigen vector

array([-0.32444284, -0.48666426,  0.81110711])

## Eighth Question

Kronecker Product = For example you have two matrices A and B, kronecker product of these two is a vector like; <<a_11*B>,...<a_nn*B>> assuming A is n*n

https://en.wikipedia.org/wiki/Kronecker_product

In [43]:
R = int(input("Enter the number of rows:"))
C = int(input("Enter the number of columns:"))
  
  
print("Enter the entries in a single line (separated by space): ")
  
# User input of entries in a 
# single line separated by space
entries = list(map(int, input().split()))
  
# For printing the matrix
matrix7 = np.array(entries).reshape(R, C)


R = int(input("Enter the number of rows:"))
C = int(input("Enter the number of columns:"))
  
  
print("Enter the entries in a single line (separated by space): ")
  
# User input of entries in a 
# single line separated by space
entries = list(map(int, input().split()))
  
# For printing the matrix
matrix8 = np.array(entries).reshape(R, C)

print(matrix7, matrix8, np.kron(matrix7, matrix8), sep = 'ğğğğğğğğğ')


Enter the number of rows:2
Enter the number of columns:2
Enter the entries in a single line (separated by space): 
1 5 7 11
Enter the number of rows:2
Enter the number of columns:2
Enter the entries in a single line (separated by space): 
11 5 77 11
[[ 1  5]
 [ 7 11]]ğğğğğğğğğ[[11  5]
 [77 11]]ğğğğğğğğğ[[ 11   5  55  25]
 [ 77  11 385  55]
 [ 77  35 121  55]
 [539  77 847 121]]


## Ninth Question

condition number is defined as $ k = ||A||||A^{-1}||$ so obviously A must be a square matrix

In [87]:
R = int(input("Enter the number of rows:"))
C = int(input("Enter the number of columns:"))
  
  
print("Enter the entries in a single line (separated by space): ")
  
# User input of entries in a 
# single line separated by space
entries = list(map(float, input().split()))
  
# For printing the matrix
F = np.array(entries).reshape(R, C)

Enter the number of rows:3
Enter the number of columns:3
Enter the entries in a single line (separated by space): 
11 27 12 14 23 1 6 9 4


In [88]:
F


array([[11., 27., 12.],
       [14., 23.,  1.],
       [ 6.,  9.,  4.]])

In [89]:
FF = F**-1


In [90]:
FFF = np.linalg.inv(F)

In [91]:
FFF

array([[-1.42857143e-01,  1.58603289e-17,  4.28571429e-01],
       [ 8.60585198e-02,  4.81927711e-02, -2.70223752e-01],
       [ 2.06540448e-02, -1.08433735e-01,  2.15146299e-01]])

In [93]:
k = np.linalg.norm(F)*np.linalg.norm(FFF)

In [94]:
k

25.29520536080166

In [95]:
print(np.linalg.cond(F))

24.239554167949773


## Tenth Question

In [47]:
pü = np.arange(3)

In [50]:
norm = np.sqrt(pü[0]**2 + pü[1]**2 + pü[2]**2) #elle

In [49]:
pü

array([0, 1, 2])

In [51]:
norm


2.23606797749979

In [52]:
püü = np.linalg.norm(pü) #numpy ile

In [53]:
püü


2.23606797749979

## Eleventh Question

In [96]:
R = int(input("Enter the number of rows:"))
C = int(input("Enter the number of columns:"))
  
  
print("Enter the entries in a single line (separated by space): ")
  
# User input of entries in a 
# single line separated by space
entries = list(map(float, input().split()))
  
# For printing the matrix
T = np.array(entries).reshape(R, C)

Enter the number of rows:3
Enter the number of columns:3
Enter the entries in a single line (separated by space): 
1 1 7 11 7 11 3 5 4


In [132]:
def f(T):
    return T[0,0]*(T[1,1]*T[2,2]-T[1,2]*T[2,1]) - T[0,1]*(T[1,0]*T[2,2]-T[2,0]*T[1,2]) + T[0,2]*(T[1,0]*T[2,1]-T[2,0]*T[1,1])
    
    

In [122]:
T[1,0]


11.0

In [109]:
T

array([[ 1.,  1.,  7.],
       [11.,  7., 11.],
       [ 3.,  5.,  4.]])

In [133]:
f(T)

200.0

In [130]:
np.linalg.det(T)

200.0000000000001

## Twelth Question

In [134]:
R = int(input("Enter the number of rows:"))
C = int(input("Enter the number of columns:"))
  
  
print("Enter the entries in a single line (separated by space): ")
  
# User input of entries in a 
# single line separated by space
entries = list(map(float, input().split()))
  
# For printing the matrix
ğğ = np.array(entries).reshape(R, C)

Enter the number of rows:2
Enter the number of columns:2
Enter the entries in a single line (separated by space): 
4 5 6 2


In [135]:
ğğ


array([[4., 5.],
       [6., 2.]])

In [140]:
def f(ğğ):
    return np.array([[ğğ[1,1], -ğğ[0,1]],[-ğğ[1,0], ğğ[0,0]]])*1/(ğğ[1,1]*ğğ[0,0] - ğğ[1,0]*ğğ[0,1])

In [141]:
f(ğğ)


array([[-0.09090909,  0.22727273],
       [ 0.27272727, -0.18181818]])

In [142]:
np.linalg.inv(ğğ)

array([[-0.09090909,  0.22727273],
       [ 0.27272727, -0.18181818]])

## Thirteenth Question

In [ ]:
?

## Fourteenth Question



In [ ]:
#bu soru 9 ile aynı

## Fifteenth Question

Sum of diagonal entries = a_00+ a_11+ a_22+ ...+ a_nn assuming A is an n * n sqaure matrix

In [143]:
R = int(input("Enter the number of rows:"))
C = int(input("Enter the number of columns:"))
  
  
print("Enter the entries in a single line (separated by space): ")
  
# User input of entries in a 
# single line separated by space
entries = list(map(float, input().split()))
  
# For printing the matrix
jj = np.array(entries).reshape(R, C)

Enter the number of rows:2
Enter the number of columns:2
Enter the entries in a single line (separated by space): 
2 5 7 11


In [144]:
jj


array([[ 2.,  5.],
       [ 7., 11.]])

In [155]:
i = 0
if i == j:
  def f(i):
    return jj[i,i] + jj[i,i]
    
    
#numpy olmadan trace i hesaplamayı denemiştim ama beceremedim

NameError: name 'j' is not defined

In [156]:
jj[i,i]

2.0

In [162]:
a = np.trace(jj)

In [163]:
a

13.0

## Sixteenth Question